/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 38.0.2 Sat Jul  8 21:08:10 2023.
 */

#include <string.h>

#include "sdc_can_pwt_db_v1_0.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int sdc_can_pwt_db_v1_0_fbms_cells_vdc_pack(
    uint8_t *dst_p,
    const struct sdc_can_pwt_db_v1_0_fbms_cells_vdc_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->fbms_cells_min_volt, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->fbms_cells_min_volt, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->fbms_cells_max_volt, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->fbms_cells_max_volt, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->fbms_vdc, 3u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->fbms_vdc, 5u, 0xe0u);
    dst_p[6] |= pack_left_shift_u8(src_p->fbms_cells_msg_cnt, 0u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->fbms_cells_checksum, 0u, 0xffu);

    return (8);
}

int sdc_can_pwt_db_v1_0_fbms_cells_vdc_unpack(
    struct sdc_can_pwt_db_v1_0_fbms_cells_vdc_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fbms_cells_min_volt = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->fbms_cells_min_volt |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->fbms_cells_max_volt = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->fbms_cells_max_volt |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->fbms_vdc = unpack_left_shift_u16(src_p[4], 3u, 0xffu);
    dst_p->fbms_vdc |= unpack_right_shift_u16(src_p[5], 5u, 0xe0u);
    dst_p->fbms_cells_msg_cnt = unpack_right_shift_u8(src_p[6], 0u, 0x0fu);
    dst_p->fbms_cells_checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint16_t sdc_can_pwt_db_v1_0_fbms_cells_vdc_fbms_cells_min_volt_encode(float value)
{
    return (uint16_t)(value / 0.000076295109483f);
}

float sdc_can_pwt_db_v1_0_fbms_cells_vdc_fbms_cells_min_volt_decode(uint16_t value)
{
    return ((float)value * 0.000076295109483f);
}

bool sdc_can_pwt_db_v1_0_fbms_cells_vdc_fbms_cells_min_volt_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sdc_can_pwt_db_v1_0_fbms_cells_vdc_fbms_cells_max_volt_encode(float value)
{
    return (uint16_t)(value / 0.000076295109483f);
}

float sdc_can_pwt_db_v1_0_fbms_cells_vdc_fbms_cells_max_volt_decode(uint16_t value)
{
    return ((float)value * 0.000076295109483f);
}

bool sdc_can_pwt_db_v1_0_fbms_cells_vdc_fbms_cells_max_volt_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sdc_can_pwt_db_v1_0_fbms_cells_vdc_fbms_vdc_encode(float value)
{
    return (uint16_t)(value / 0.294117647058824f);
}

float sdc_can_pwt_db_v1_0_fbms_cells_vdc_fbms_vdc_decode(uint16_t value)
{
    return ((float)value * 0.294117647058824f);
}

bool sdc_can_pwt_db_v1_0_fbms_cells_vdc_fbms_vdc_is_in_range(uint16_t value)
{
    return (value <= 2046u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_cells_vdc_fbms_cells_msg_cnt_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_cells_vdc_fbms_cells_msg_cnt_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_cells_vdc_fbms_cells_msg_cnt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_cells_vdc_fbms_cells_checksum_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_cells_vdc_fbms_cells_checksum_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_cells_vdc_fbms_cells_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int sdc_can_pwt_db_v1_0_bcm_vehicle_status_pack(
    uint8_t *dst_p,
    const struct sdc_can_pwt_db_v1_0_bcm_vehicle_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bcm_charge_req, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->bcm_clear_latched_errors, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->bcm_contactors_mode, 0u, 0x03u);
    dst_p[6] |= pack_left_shift_u8(src_p->bcm_msg_cnt, 0u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->bcm_vehicle_status_checksum, 0u, 0xffu);

    return (8);
}

int sdc_can_pwt_db_v1_0_bcm_vehicle_status_unpack(
    struct sdc_can_pwt_db_v1_0_bcm_vehicle_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bcm_charge_req = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->bcm_clear_latched_errors = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->bcm_contactors_mode = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->bcm_msg_cnt = unpack_right_shift_u8(src_p[6], 0u, 0x0fu);
    dst_p->bcm_vehicle_status_checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t sdc_can_pwt_db_v1_0_bcm_vehicle_status_bcm_charge_req_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_bcm_vehicle_status_bcm_charge_req_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_bcm_vehicle_status_bcm_charge_req_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_bcm_vehicle_status_bcm_clear_latched_errors_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_bcm_vehicle_status_bcm_clear_latched_errors_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_bcm_vehicle_status_bcm_clear_latched_errors_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_bcm_vehicle_status_bcm_contactors_mode_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_bcm_vehicle_status_bcm_contactors_mode_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_bcm_vehicle_status_bcm_contactors_mode_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t sdc_can_pwt_db_v1_0_bcm_vehicle_status_bcm_msg_cnt_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_bcm_vehicle_status_bcm_msg_cnt_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_bcm_vehicle_status_bcm_msg_cnt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t sdc_can_pwt_db_v1_0_bcm_vehicle_status_bcm_vehicle_status_checksum_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_bcm_vehicle_status_bcm_vehicle_status_checksum_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_bcm_vehicle_status_bcm_vehicle_status_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int sdc_can_pwt_db_v1_0_fbms_limits_pack(
    uint8_t *dst_p,
    const struct sdc_can_pwt_db_v1_0_fbms_limits_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->fbms_max_output_curr, 4u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->fbms_max_output_curr, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->fbms_max_regen_curr, 8u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->fbms_max_regen_curr, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->fbms_max_output_pow, 4u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->fbms_max_output_pow, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u16(src_p->fbms_max_regen_pow, 8u, 0x0fu);
    dst_p[5] |= pack_left_shift_u16(src_p->fbms_max_regen_pow, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->fbms_traction_en, 7u, 0x80u);
    dst_p[6] |= pack_left_shift_u8(src_p->fbms_regen_brake_en, 6u, 0x40u);
    dst_p[6] |= pack_left_shift_u8(src_p->fbms_de_energize_req, 5u, 0x20u);
    dst_p[6] |= pack_left_shift_u8(src_p->fbms_limits_msg_cnt, 0u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->fbms_limits_checksum, 0u, 0xffu);

    return (8);
}

int sdc_can_pwt_db_v1_0_fbms_limits_unpack(
    struct sdc_can_pwt_db_v1_0_fbms_limits_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fbms_max_output_curr = unpack_left_shift_u16(src_p[0], 4u, 0xffu);
    dst_p->fbms_max_output_curr |= unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->fbms_max_regen_curr = unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->fbms_max_regen_curr |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->fbms_max_output_pow = unpack_left_shift_u16(src_p[3], 4u, 0xffu);
    dst_p->fbms_max_output_pow |= unpack_right_shift_u16(src_p[4], 4u, 0xf0u);
    dst_p->fbms_max_regen_pow = unpack_left_shift_u16(src_p[4], 8u, 0x0fu);
    dst_p->fbms_max_regen_pow |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->fbms_traction_en = unpack_right_shift_u8(src_p[6], 7u, 0x80u);
    dst_p->fbms_regen_brake_en = unpack_right_shift_u8(src_p[6], 6u, 0x40u);
    dst_p->fbms_de_energize_req = unpack_right_shift_u8(src_p[6], 5u, 0x20u);
    dst_p->fbms_limits_msg_cnt = unpack_right_shift_u8(src_p[6], 0u, 0x0fu);
    dst_p->fbms_limits_checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint16_t sdc_can_pwt_db_v1_0_fbms_limits_fbms_max_output_curr_encode(float value)
{
    return (uint16_t)(value / 0.05f);
}

float sdc_can_pwt_db_v1_0_fbms_limits_fbms_max_output_curr_decode(uint16_t value)
{
    return ((float)value * 0.05f);
}

bool sdc_can_pwt_db_v1_0_fbms_limits_fbms_max_output_curr_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t sdc_can_pwt_db_v1_0_fbms_limits_fbms_max_regen_curr_encode(float value)
{
    return (uint16_t)(value / 0.05f);
}

float sdc_can_pwt_db_v1_0_fbms_limits_fbms_max_regen_curr_decode(uint16_t value)
{
    return ((float)value * 0.05f);
}

bool sdc_can_pwt_db_v1_0_fbms_limits_fbms_max_regen_curr_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t sdc_can_pwt_db_v1_0_fbms_limits_fbms_max_output_pow_encode(float value)
{
    return (uint16_t)(value / 0.05f);
}

float sdc_can_pwt_db_v1_0_fbms_limits_fbms_max_output_pow_decode(uint16_t value)
{
    return ((float)value * 0.05f);
}

bool sdc_can_pwt_db_v1_0_fbms_limits_fbms_max_output_pow_is_in_range(uint16_t value)
{
    return (value <= 4000u);
}

uint16_t sdc_can_pwt_db_v1_0_fbms_limits_fbms_max_regen_pow_encode(float value)
{
    return (uint16_t)(value / 0.05f);
}

float sdc_can_pwt_db_v1_0_fbms_limits_fbms_max_regen_pow_decode(uint16_t value)
{
    return ((float)value * 0.05f);
}

bool sdc_can_pwt_db_v1_0_fbms_limits_fbms_max_regen_pow_is_in_range(uint16_t value)
{
    return (value <= 4000u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_limits_fbms_traction_en_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_limits_fbms_traction_en_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_limits_fbms_traction_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_limits_fbms_regen_brake_en_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_limits_fbms_regen_brake_en_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_limits_fbms_regen_brake_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_limits_fbms_de_energize_req_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_limits_fbms_de_energize_req_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_limits_fbms_de_energize_req_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_limits_fbms_limits_msg_cnt_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_limits_fbms_limits_msg_cnt_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_limits_fbms_limits_msg_cnt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_limits_fbms_limits_checksum_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_limits_fbms_limits_checksum_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_limits_fbms_limits_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int sdc_can_pwt_db_v1_0_fbms_charge_pack(
    uint8_t *dst_p,
    const struct sdc_can_pwt_db_v1_0_fbms_charge_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->fbms_charge_sts, 6u, 0xc0u);
    dst_p[0] |= pack_left_shift_u8(src_p->fbms_balancing, 5u, 0x20u);
    dst_p[0] |= pack_right_shift_u16(src_p->fbms_charge_max_curr, 8u, 0x0fu);
    dst_p[1] |= pack_left_shift_u16(src_p->fbms_charge_max_curr, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->fbms_charge_max_volt, 5u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->fbms_charge_max_volt, 3u, 0xf8u);
    dst_p[3] |= pack_right_shift_u16(src_p->fbms_unbalance, 7u, 0x07u);
    dst_p[4] |= pack_left_shift_u16(src_p->fbms_unbalance, 1u, 0xfeu);
    dst_p[6] |= pack_left_shift_u8(src_p->fbms_charge_msg_cnt, 0u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->fbms_charge_checksum, 0u, 0xffu);

    return (8);
}

int sdc_can_pwt_db_v1_0_fbms_charge_unpack(
    struct sdc_can_pwt_db_v1_0_fbms_charge_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fbms_charge_sts = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);
    dst_p->fbms_balancing = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->fbms_charge_max_curr = unpack_left_shift_u16(src_p[0], 8u, 0x0fu);
    dst_p->fbms_charge_max_curr |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->fbms_charge_max_volt = unpack_left_shift_u16(src_p[2], 5u, 0xffu);
    dst_p->fbms_charge_max_volt |= unpack_right_shift_u16(src_p[3], 3u, 0xf8u);
    dst_p->fbms_unbalance = unpack_left_shift_u16(src_p[3], 7u, 0x07u);
    dst_p->fbms_unbalance |= unpack_right_shift_u16(src_p[4], 1u, 0xfeu);
    dst_p->fbms_charge_msg_cnt = unpack_right_shift_u8(src_p[6], 0u, 0x0fu);
    dst_p->fbms_charge_checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_charge_fbms_charge_sts_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_charge_fbms_charge_sts_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_charge_fbms_charge_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_charge_fbms_balancing_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_charge_fbms_balancing_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_charge_fbms_balancing_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t sdc_can_pwt_db_v1_0_fbms_charge_fbms_charge_max_curr_encode(float value)
{
    return (uint16_t)(value / 0.05f);
}

float sdc_can_pwt_db_v1_0_fbms_charge_fbms_charge_max_curr_decode(uint16_t value)
{
    return ((float)value * 0.05f);
}

bool sdc_can_pwt_db_v1_0_fbms_charge_fbms_charge_max_curr_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t sdc_can_pwt_db_v1_0_fbms_charge_fbms_charge_max_volt_encode(float value)
{
    return (uint16_t)(value / 0.0769230769230769f);
}

float sdc_can_pwt_db_v1_0_fbms_charge_fbms_charge_max_volt_decode(uint16_t value)
{
    return ((float)value * 0.0769230769230769f);
}

bool sdc_can_pwt_db_v1_0_fbms_charge_fbms_charge_max_volt_is_in_range(uint16_t value)
{
    return (value <= 8191u);
}

uint16_t sdc_can_pwt_db_v1_0_fbms_charge_fbms_unbalance_encode(float value)
{
    return (uint16_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_charge_fbms_unbalance_decode(uint16_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_charge_fbms_unbalance_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_charge_fbms_charge_msg_cnt_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_charge_fbms_charge_msg_cnt_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_charge_fbms_charge_msg_cnt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_charge_fbms_charge_checksum_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_charge_fbms_charge_checksum_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_charge_fbms_charge_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int sdc_can_pwt_db_v1_0_fbms_status_pack(
    uint8_t *dst_p,
    const struct sdc_can_pwt_db_v1_0_fbms_status_t *src_p,
    size_t size)
{
    uint16_t fbms_act_power;
    uint16_t fbms_battery_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->fbms_contactors_sts, 6u, 0xc0u);
    dst_p[0] |= pack_left_shift_u8(src_p->fbms_fault, 5u, 0x20u);
    dst_p[1] |= pack_right_shift_u16(src_p->fbms_battery_voltage, 3u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->fbms_battery_voltage, 5u, 0xe0u);
    fbms_battery_current = (uint16_t)src_p->fbms_battery_current;
    dst_p[2] |= pack_right_shift_u16(fbms_battery_current, 8u, 0x1fu);
    dst_p[3] |= pack_left_shift_u16(fbms_battery_current, 0u, 0xffu);
    fbms_act_power = (uint16_t)src_p->fbms_act_power;
    dst_p[4] |= pack_right_shift_u16(fbms_act_power, 4u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(fbms_act_power, 4u, 0xf0u);
    dst_p[5] |= pack_right_shift_u8(src_p->fbms_so_c, 4u, 0x0fu);
    dst_p[6] |= pack_left_shift_u8(src_p->fbms_so_c, 4u, 0xf0u);
    dst_p[6] |= pack_left_shift_u8(src_p->fbms_msg_cnt, 0u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->fbms_status_checksum, 0u, 0xffu);

    return (8);
}

int sdc_can_pwt_db_v1_0_fbms_status_unpack(
    struct sdc_can_pwt_db_v1_0_fbms_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t fbms_act_power;
    uint16_t fbms_battery_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fbms_contactors_sts = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);
    dst_p->fbms_fault = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->fbms_battery_voltage = unpack_left_shift_u16(src_p[1], 3u, 0xffu);
    dst_p->fbms_battery_voltage |= unpack_right_shift_u16(src_p[2], 5u, 0xe0u);
    fbms_battery_current = unpack_left_shift_u16(src_p[2], 8u, 0x1fu);
    fbms_battery_current |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);

    if ((fbms_battery_current & (1u << 12)) != 0u) {
        fbms_battery_current |= 0xe000u;
    }

    dst_p->fbms_battery_current = (int16_t)fbms_battery_current;
    fbms_act_power = unpack_left_shift_u16(src_p[4], 4u, 0xffu);
    fbms_act_power |= unpack_right_shift_u16(src_p[5], 4u, 0xf0u);

    if ((fbms_act_power & (1u << 11)) != 0u) {
        fbms_act_power |= 0xf000u;
    }

    dst_p->fbms_act_power = (int16_t)fbms_act_power;
    dst_p->fbms_so_c = unpack_left_shift_u8(src_p[5], 4u, 0x0fu);
    dst_p->fbms_so_c |= unpack_right_shift_u8(src_p[6], 4u, 0xf0u);
    dst_p->fbms_msg_cnt = unpack_right_shift_u8(src_p[6], 0u, 0x0fu);
    dst_p->fbms_status_checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_status_fbms_contactors_sts_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_status_fbms_contactors_sts_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_status_fbms_contactors_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_status_fbms_fault_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_status_fbms_fault_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_status_fbms_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t sdc_can_pwt_db_v1_0_fbms_status_fbms_battery_voltage_encode(float value)
{
    return (uint16_t)(value / 0.294117647058824f);
}

float sdc_can_pwt_db_v1_0_fbms_status_fbms_battery_voltage_decode(uint16_t value)
{
    return ((float)value * 0.294117647058824f);
}

bool sdc_can_pwt_db_v1_0_fbms_status_fbms_battery_voltage_is_in_range(uint16_t value)
{
    return (value <= 2046u);
}

int16_t sdc_can_pwt_db_v1_0_fbms_status_fbms_battery_current_encode(float value)
{
    return (int16_t)(value / 0.05f);
}

float sdc_can_pwt_db_v1_0_fbms_status_fbms_battery_current_decode(int16_t value)
{
    return ((float)value * 0.05f);
}

bool sdc_can_pwt_db_v1_0_fbms_status_fbms_battery_current_is_in_range(int16_t value)
{
    return ((value >= -4096) && (value <= 4095));
}

int16_t sdc_can_pwt_db_v1_0_fbms_status_fbms_act_power_encode(float value)
{
    return (int16_t)(value / 0.1f);
}

float sdc_can_pwt_db_v1_0_fbms_status_fbms_act_power_decode(int16_t value)
{
    return ((float)value * 0.1f);
}

bool sdc_can_pwt_db_v1_0_fbms_status_fbms_act_power_is_in_range(int16_t value)
{
    return ((value >= -2000) && (value <= 2000));
}

uint8_t sdc_can_pwt_db_v1_0_fbms_status_fbms_so_c_encode(float value)
{
    return (uint8_t)(value / 0.5f);
}

float sdc_can_pwt_db_v1_0_fbms_status_fbms_so_c_decode(uint8_t value)
{
    return ((float)value * 0.5f);
}

bool sdc_can_pwt_db_v1_0_fbms_status_fbms_so_c_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_status_fbms_msg_cnt_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_status_fbms_msg_cnt_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_status_fbms_msg_cnt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_status_fbms_status_checksum_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_status_fbms_status_checksum_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_status_fbms_status_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int sdc_can_pwt_db_v1_0_fbms_warn_err_pack(
    uint8_t *dst_p,
    const struct sdc_can_pwt_db_v1_0_fbms_warn_err_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->fbms_warn_insulation, 7u, 0x80u);
    dst_p[0] |= pack_left_shift_u8(src_p->fbms_warn_over_current, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->fbms_warn_limits_by_temp, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->fbms_warn_limits_by_volt, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->fbms_warn_no_regen_brake, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->fbms_err_insulation, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->fbms_err_over_current, 4u, 0x10u);
    dst_p[2] |= pack_left_shift_u8(src_p->fbms_err_contactors, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->fbms_err_over_voltage, 2u, 0x04u);
    dst_p[2] |= pack_left_shift_u8(src_p->fbms_err_under_voltage, 1u, 0x02u);
    dst_p[3] |= pack_left_shift_u8(src_p->fbms_err_over_temp, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u8(src_p->fbms_err_under_temp, 6u, 0x40u);
    dst_p[3] |= pack_left_shift_u8(src_p->fbms_err_system_fault, 5u, 0x20u);
    dst_p[3] |= pack_left_shift_u8(src_p->fbms_err_battery_fault, 2u, 0x04u);
    dst_p[3] |= pack_left_shift_u8(src_p->fbms_err_current_sensor_ko, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->fbms_err_lt_insulation, 7u, 0x80u);
    dst_p[4] |= pack_left_shift_u8(src_p->fbms_err_lt_over_current, 4u, 0x10u);
    dst_p[4] |= pack_left_shift_u8(src_p->fbms_err_lt_contactors, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u8(src_p->fbms_err_lt_over_voltage, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->fbms_err_lt_under_voltage, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->fbms_err_lt_over_temp, 7u, 0x80u);
    dst_p[5] |= pack_left_shift_u8(src_p->fbms_err_lt_under_temp, 6u, 0x40u);
    dst_p[5] |= pack_left_shift_u8(src_p->fbms_err_lt_system_fault, 5u, 0x20u);
    dst_p[5] |= pack_left_shift_u8(src_p->fbms_err_lt_battery_fault, 2u, 0x04u);
    dst_p[5] |= pack_left_shift_u8(src_p->fbms_err_lt_current_sensor_ko, 1u, 0x02u);
    dst_p[6] |= pack_left_shift_u8(src_p->fbms_warn_err_msg_cnt, 0u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->fbms_warn_err_checksum, 0u, 0xffu);

    return (8);
}

int sdc_can_pwt_db_v1_0_fbms_warn_err_unpack(
    struct sdc_can_pwt_db_v1_0_fbms_warn_err_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fbms_warn_insulation = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->fbms_warn_over_current = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->fbms_warn_limits_by_temp = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->fbms_warn_limits_by_volt = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->fbms_warn_no_regen_brake = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->fbms_err_insulation = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->fbms_err_over_current = unpack_right_shift_u8(src_p[2], 4u, 0x10u);
    dst_p->fbms_err_contactors = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->fbms_err_over_voltage = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->fbms_err_under_voltage = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->fbms_err_over_temp = unpack_right_shift_u8(src_p[3], 7u, 0x80u);
    dst_p->fbms_err_under_temp = unpack_right_shift_u8(src_p[3], 6u, 0x40u);
    dst_p->fbms_err_system_fault = unpack_right_shift_u8(src_p[3], 5u, 0x20u);
    dst_p->fbms_err_battery_fault = unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->fbms_err_current_sensor_ko = unpack_right_shift_u8(src_p[3], 1u, 0x02u);
    dst_p->fbms_err_lt_insulation = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->fbms_err_lt_over_current = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->fbms_err_lt_contactors = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->fbms_err_lt_over_voltage = unpack_right_shift_u8(src_p[4], 2u, 0x04u);
    dst_p->fbms_err_lt_under_voltage = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->fbms_err_lt_over_temp = unpack_right_shift_u8(src_p[5], 7u, 0x80u);
    dst_p->fbms_err_lt_under_temp = unpack_right_shift_u8(src_p[5], 6u, 0x40u);
    dst_p->fbms_err_lt_system_fault = unpack_right_shift_u8(src_p[5], 5u, 0x20u);
    dst_p->fbms_err_lt_battery_fault = unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->fbms_err_lt_current_sensor_ko = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->fbms_warn_err_msg_cnt = unpack_right_shift_u8(src_p[6], 0u, 0x0fu);
    dst_p->fbms_warn_err_checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_insulation_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_insulation_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_insulation_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_over_current_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_over_current_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_over_current_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_limits_by_temp_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_limits_by_temp_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_limits_by_temp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_limits_by_volt_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_limits_by_volt_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_limits_by_volt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_no_regen_brake_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_no_regen_brake_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_no_regen_brake_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_insulation_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_insulation_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_insulation_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_over_current_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_over_current_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_over_current_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_contactors_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_contactors_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_contactors_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_over_voltage_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_over_voltage_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_over_voltage_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_under_voltage_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_under_voltage_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_under_voltage_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_over_temp_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_over_temp_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_over_temp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_under_temp_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_under_temp_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_under_temp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_system_fault_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_system_fault_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_system_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_battery_fault_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_battery_fault_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_battery_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_current_sensor_ko_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_current_sensor_ko_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_current_sensor_ko_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_insulation_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_insulation_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_insulation_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_over_current_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_over_current_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_over_current_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_contactors_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_contactors_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_contactors_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_over_voltage_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_over_voltage_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_over_voltage_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_under_voltage_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_under_voltage_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_under_voltage_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_over_temp_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_over_temp_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_over_temp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_under_temp_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_under_temp_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_under_temp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_system_fault_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_system_fault_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_system_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_battery_fault_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_battery_fault_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_battery_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_current_sensor_ko_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_current_sensor_ko_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_err_lt_current_sensor_ko_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_err_msg_cnt_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_err_msg_cnt_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_err_msg_cnt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_err_checksum_encode(float value)
{
    return (uint8_t)(value);
}

float sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_err_checksum_decode(uint8_t value)
{
    return ((float)value);
}

bool sdc_can_pwt_db_v1_0_fbms_warn_err_fbms_warn_err_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
